server:
  port: 8999
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # time zone config
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# common mybatis plus config
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mybatis:
  mapper-locations: classpath:/mapper/*.xml